stages:
  - test
  - deploy

test:
  stage: test
  script:
    - docker run --rm -v $(pwd):/code:ro -w /code --entrypoint=/code/ci/test.sh bluetab/amazonlinux-python3-neo4j:20180424163150279987171
  artifacts:
    untracked: true

deploy:
  stage: deploy
  environment:
    name: prod
  only:
    - master
  script:
    - git branch -f master HEAD
    - export VERSION=$(cat version)
    - docker build -t bluetab-truedat/$CI_PROJECT_NAME:latest .
    - docker run --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION mesosphere/aws-cli ecr get-login --no-include-email --region $AWS_DEFAULT_REGION | awk '{ sub("\r$", ""); print }' > output
    - bash -f output
    - export ECR=$(cat output | egrep -o 'https?://[^ ]+' | awk -F/ '{print $3}')
    - rm output
    - docker tag bluetab-truedat/$CI_PROJECT_NAME:latest $ECR/bluetab-truedat/$CI_PROJECT_NAME:latest
    - docker tag bluetab-truedat/$CI_PROJECT_NAME:latest $ECR/bluetab-truedat/$CI_PROJECT_NAME:${VERSION}
    - docker push $ECR/bluetab-truedat/$CI_PROJECT_NAME:latest
    - docker push $ECR/bluetab-truedat/$CI_PROJECT_NAME:${VERSION}
    - docker run --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION -e ECS_CLUSTER -e ECS_SERVICE mesosphere/aws-cli ecs update-service --force-new-deployment --cluster $ECS_CLUSTER --service $ECS_SERVICE
    # - docker run --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION -e ECS_CLUSTER -e ECS_SERVICE mesosphere/aws-cli ecs wait services-stable --cluster $ECS_CLUSTER --services $ECS_SERVICE
