stages:
  - test
  - deploy

test:
  stage: test
  script:
    - docker run --rm -v $(pwd):/code:ro -w /code --entrypoint=/code/ci/test.sh bluetab/amazonlinux-python3-neo4j:20180123125610087277324
  artifacts:
    untracked: true

deploy:
  stage: deploy
  script:
    - git branch -f master HEAD
    - export NEO4J_PASSWORD=$(echo $NEO4J_PASSWORD | sed -e "s/\//\\\\\//g")
    - export DB_HOST=$(echo $DB_HOST | sed -e "s/\//\\\\\//g")
    - export GUARDIAN_SECRET_KEY=$(echo $GUARDIAN_SECRET_KEY | sed -e "s/\//\\\\\//g")
    - export PRODUCTION_HOST=$(cat .deliver/config | grep PRODUCTION_HOSTS | cut -f2 -d"=" | sed -e 's/"//g')
    - export PRODUCTION_USER=$(cat .deliver/config | grep PRODUCTION_USER | cut -f2 -d"=" | sed -e 's/"//g')
    - docker run --rm -e NEO4J_PASSWORD=$NEO4J_PASSWORD -e PRODUCTION_HOST=$PRODUCTION_HOST -e PRODUCTION_USER=$PRODUCTION_USER -e PRODUCTION_PEM="$PRODUCTION_PEM" -e GUARDIAN_SECRET_KEY="$GUARDIAN_SECRET_KEY" -e USER=$USER -e BUILD_AT=$BUILD_AT -e TERM=$TERM -v $(pwd):/code:ro -w /code --entrypoint=/code/ci/deploy.sh bluetab/amazonlinux-python3-neo4j:20180123125610087277324
  only:
    - master
